apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ufkq6116p-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ufkq6116p-python 
  name: ufkq6116p-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ufkq6116p-python 
